=== nivetha-r/Mode2Training/Mode2/MDay2/xmlDemo/WebContent/WEB-INF/Employee.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Employee">
    <xs:complexType>
      <xs:sequence>
         <xs:element name="Emp" maxOccurs="unbounded">
           <xs:complexType>
              <xs:sequence>
   
     			 
 <xs:element name="empNo" >    			 
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="empName">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="([a-zA-Z])*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="salary"> 
 <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
     			 
      			 
 <xs:element name="band">     			 
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[CME]"/>
      <xs:maxLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
      			 <xs:element name="dateOfJoin">
      			  <xs:simpleType>
    <xs:restriction base="xs:date">
      <xs:minInclusive value="2019-09-18"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
     </xs:element>
   </xs:schema>

=== nivetha-r/Mode2Training/Mode2/MDay2/xmlDemo/WebContent/WEB-INF/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>


<Employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNameSpaceschemaLocation="Employee.xsd">


<Emp>
<empNo>41</empNo>
<empName>Nivetha</empName>
<salary>10000</salary>
<dateOfJoin>2019-07-10</dateOfJoin>
<band>M</band>
</Emp>

<Emp>
<empNo>21</empNo>
<empName>Nivi</empName>
<salary>10000</salary>
<dateOfJoin>2019-06-09</dateOfJoin>
<band>E</band>
</Emp>

<Emp>
<empNo>33</empNo>
<empName>Rajamani</empName>
<salary>8000</salary>
<dateOfJoin>2014-08-15</dateOfJoin>
<band>C</band>
</Emp>

</Employee>
